title: "Fabrice Van Boeckel"
description: "Data Scientist"
theme: jekyll-theme-cayman
url: "https://fabricevb.github.io" # Your GitHub Pages URL
baseurl: "" # Leave this blank unless your site is in a subdirectory

# Social Links
social_links:
  - name: GitHub
    url: https://github.com/fabricevb
  - name: LinkedIn
    url: https://www.linkedin.com/in/fabricevb/


# Optional: Markdown settings
markdown: kramdown
highlighter: rouge
